### ISSUE TITLE
declarationMap source file relative path problem

### ISSUE THREAD

**Issue by rafaeldeoliveira** [run-z/rollup-plugin-flat-dts#16]
Hi,

Great work on this plugin!

My index.d.ts.map is being generated with wrong source files path.
The output dir is `./dist/esm/`, and the generated index.d.ts.map contains the following:
`{"version":3,"sources":["src/styles.ts","src/Separator.tsx"],"names":[],"mappings":";IAEA,M ........`
I belive the sources array should be `["../../src/styles.ts","../../src/Separator.tsx"]`, so the IDE jump-click works.

do you belive it is a configuration related issue?

**Comment by surol** [comment]
Thanks for report.
That's definitely a bug.

**Comment by surol** [comment]
Fixed in release [1.2.3](https://github.com/run-z/rollup-plugin-flat-dts/releases/tag/v1.2.3)
