### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by mrazauskas** [run-z/rollup-plugin-flat-dts#21]
Trying to use `rollup-plugin-flat-dts` with an Node.js project published in ESM syntax and TypeScript 5 and getting the following errors:

- TS5053: Option 'outFile' cannot be specified with option 'verbatimModuleSyntax'.
- TS5105: Option 'verbatimModuleSyntax' cannot be used when 'module' is set to 'UMD', 'AMD', or 'System'.
- TS2441: Duplicate identifier 'require'. Compiler reserves name 'require' in top level scope of a module.

I could try to work around the first two, but the last one is not so easy. This is an ESM package and to have `require` I need to call `createRequire()`. `rollup-plugin-flat-dts` does not allow that. Hm.. Tricky.

**Comment by surol** [comment]
The first two happen because the plugin sets `module` to `System` in order to operate. The option `verbatimModuleSyntax` can be overridden in this case with `compilerOptions` plugin option.

The third one is weird. It seems TypeScript doesn't like the `require` symbol name. Rename it perhaps?
```typescript
const nodeRequire = createRequire(...);`.
```

**Comment by mrazauskas** [comment]
Thanks for quick reply. Renaming could work, I will give it a try.
