### ISSUE TITLE
How to support json import

### ISSUE THREAD

**Issue by yanjunze** [run-z/rollup-plugin-flat-dts#22]
Thank you for your plugin.
I am now use the plugin with Typescript 5.
Because there is some '*.json' in my project, so I set 
```json
{
  "resolveJsonModule": true,
  "module": "ESNext"
}
```
in my tsconfig. 

but the plugin print error like this:
```bash
[!] (plugin flat-dts) RollupError: error TS5071: Option '--resolveJsonModule' can only be specified when module code generation is 'commonjs', 'amd', 'es2015' or 'esNext'.
```
I saw the plugin over the config `module` to 'system'，so the error print.

So how can i use the plugin with json import like `import './lang.json;'` in ts and tsx.

If the json can not support, could over the tsconfig `resolveJsonModule` to false, because the `module: system` can not resolve json.

**Comment by surol** [comment]
With `compilerOptions` the `resolveJsonModule` can be disabled:

```javascript
flatDts({
  compilerOptions: {
    resolveJsonModule: false,
  }
})
```

I guess this is yet another flag to disable automatically :(

**Comment by yanjunze** [comment]
Thank you for your advise.
Now i use the `resolveJsonModule: false` in my rollup config.
But the json import print some error when i build my project like this:
 
![image](https://github.com/run-z/rollup-plugin-flat-dts/assets/17762697/9ba3227d-04e3-4ee4-b579-88f801bcaf7d)

Is there some way to support json import?

**Comment by surol** [comment]
Ah, I see.
The other options would be to try create `tsconfig` for `.d.ts` generation. Something like that:
```json
{
  "extends": "./tsconfig.json",
  "include": [],
  "files": ["src/index.ts"]
}
```
If `src/index.ts` exports everything you want and does not import JSON (directly or indirectly), then this should help.
Otherwise, it is unavoidable.

**Comment by yanjunze** [comment]
Thank you very much! :)

 But in my project, I need to import json in my entry indirectly. (I am using the multi entry mode)
 Recently I add `declare module '*.json'` in my @types file. And now json import not print error.
 
 But also i think you can add `resolveJsonModule: false` in code to avoid this situation:
 ```typescript
 const MANDATORY_COMPILER_OPTIONS = {
    // Avoid extra work
    checkJs: false,
    // Ensure ".d.ts" modules are generated
    declaration: true,
    // Prevent output to declaration directory
    declarationDir: undefined,
    // Skip ".js" generation
    emitDeclarationOnly: true,
    // Single file emission is impossible with this flag set
    isolatedModules: false,
    // Generate single file
    // `System`, in contrast to `None`, permits the use of `import.meta`
    module: ts.ModuleKind.System,
    // Always emit
    noEmit: false,
    // Skip code generation when error occurs
    noEmitOnError: true,
    // Ignore errors in library type definitions
    skipLibCheck: true,
    // Always strip internal exports
    stripInternal: true,
    // Unsupported by SystemJS
    verbatimModuleSyntax: false,
};
 ```
