### ISSUE TITLE
React native style  ".native.ts" will create type overlaps

### ISSUE THREAD

**Issue by natew** [run-z/rollup-plugin-flat-dts#6]
Noticed this in [SnackUI](https://github.com/snackui/snackui) today. The use of the same exports in a `.native.ts` file will cause overlaps in the bundled output.

This one seems a bit simpler than sourcemaps, as I think we could have simple rules to decide which to select.

Not sure which is better, allowing config based on filename, or more programmatic (`filterTypes: (fileName, types) => )` maybe).

**Comment by surol** [comment]
Sorry, did not understand this. What kind of overlaps?

The tool adds nothing to the generated `.d.ts` file. Just renames modules and removes some declaration.
Any abnormally means incorrect original `.d.ts` file.

Can you provide a simple repro?

**Comment by natew** [comment]
I think it has to do with the name collision issue, if you have:

`src/Component.ts` with:

```
export type uid = number
```

and also have `src/Component.native.ts` with the same code, you'll get an error. I noticed that TypeScript seems to just choose one of them for you, so it's not a big deal for me, though it'd be nice to be able to choose.

**Comment by surol** [comment]
Just marking any unwanted symbol as with `@internal` jsdoc comment would exclude it from exports.

There is also an `internal` option. Setting it to something like `**/*.native` would exclude every `.native.ts` file from export. Would it help?
